### ISSUE TITLE
Invalid gem

### ISSUE THREAD

**Issue by chauncey-garrett** [octopress/quote-tag#1]
If I had to guess, it's because of the name change (quote-tag -> octopress-quote-tag).

**Comment by justinrummel** [comment]
Getting the same error even though it is listed in my Gemfile

`````` bash
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Could not find gem 'octopress-quote-tag (>= 0) ruby' in the gems available on this machine.```
``````

**Comment by imathis** [comment]
I hadn't released it. Oops! 1.0.0 is out now. Should work :)
