### ISSUE TITLE
Looking for "quote" vs. "blockquote" error

### ISSUE THREAD

**Issue by justinrummel** [octopress/quote-tag#2]
In reference to [this suggestion](https://github.com/octopress/feeds/issues/4#issuecomment-68934532) and use the quote-tag vs. pulling in the old Octopress 2 blockquote.rb plugin, I get the error: 

``` bash
Generating... 
Liquid Exception: Unknown tag 'blockquote' in _posts/2012-01-23-working-with-ipv6-and-mac-os-x.md
jekyll 2.5.3 | Error:  Unknown tag 'blockquote'
```

I believe it is still looking for the "quote" liquid tag even though the README.md first states blockquote.

**Comment by imathis** [comment]
Are you sure you installed it in your gemfile or your gems list properly? The tag registers as both `quote` and `blockquote` here: https://github.com/octopress/quote-tag/blob/master/lib/octopress-quote-tag.rb#L129

**Comment by justinrummel** [comment]
You are correct.  I must have been referencing the original commit instructions on the README.  I see they have now changed.  updated and it works as expected.
