### ISSUE TITLE
Consider adding support for a floating quote

### ISSUE THREAD

**Issue by chauncey-garrett** [octopress/quote-tag#3]
I've always liked having quotes floating either to the right of left of the text (much like a nice magazine article). To me, it makes the text flow well and looks very professional. Still, some quotes are best left inline (especially long ones taken from another source). Thus, it'd be nice to be able to pass a quote-left, quote(-center), and quote-right class into the HTML depending on how I desire to format the text.

**Comment by imathis** [comment]
I think you're looking for the [pullquote-tag](https://github.com/octopress/pullquote-tag). I don't have any CSS to go with it right now. I need to hook it up to Octopress ink like the octopress-solarized plugin. But you should be able to put something together pretty easily. There's even a link in the docs to a site with some CSS for such thing.

**Comment by chauncey-garrett** [comment]
Ahh, thanks! I'll look into it.
