### ISSUE TITLE
Tag a new release for Jekyll 3 support

### ISSUE THREAD

**Issue by Siosm** [octopress/quote-tag#7]
This would simplify Gemfile configs and make new Jekyll setups work by default.

Thanks.

**Comment by flxai** [comment]
Could you please have a look into this? @parkr @imathis

**Comment by parkr** [comment]
Hey! Is `master` ready for use with Jekyll 3?

Looks like Brandon is the owner of this on RubyGems.org so we'll need to have him push the update: https://rubygems.org/gems/octopress-quote-tag

**Comment by Siosm** [comment]
Closing as this will probably never happen (and I don't use this anymore). Feel free to reopen / open your own issue if needed.
